# Assignment 7

In [1]:
import numpy as np
import pandas as pd

### Q1 Write a function so that the columns of the output matrix are powers of the input vector.

In [2]:
a = np.array([1,2,3,4,5,6,7,8,9,10])

In [3]:
# inbuilt function vander
v = np.vander(a, N=3)
v

array([[  1,   1,   1],
       [  4,   2,   1],
       [  9,   3,   1],
       [ 16,   4,   1],
       [ 25,   5,   1],
       [ 36,   6,   1],
       [ 49,   7,   1],
       [ 64,   8,   1],
       [ 81,   9,   1],
       [100,  10,   1]])

In [4]:
# 1st way to create Vander function

def Vander_1(arr, N):
    g = np.stack(((arr**(N-i-1) for i in range(N)))).T
    print(g)

In [5]:
f = np.array([1,2,3,4,5,6,7,8,9,10])
N = 5
Vander_1(f, N)

[[    1     1     1     1     1]
 [   16     8     4     2     1]
 [   81    27     9     3     1]
 [  256    64    16     4     1]
 [  625   125    25     5     1]
 [ 1296   216    36     6     1]
 [ 2401   343    49     7     1]
 [ 4096   512    64     8     1]
 [ 6561   729    81     9     1]
 [10000  1000   100    10     1]]


/home/khyati/.local/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3417: FutureWarning: arrays to stack must be passed as a "sequence" type such as list or tuple. Support for non-sequence iterables such as generators is deprecated as of NumPy 1.16 and will raise an error in the future.
  exec(code_obj, self.user_global_ns, self.user_ns)


In [6]:
# 2nd way to create Vander function

def Vander_2(arr, N):
    arr = arr.reshape(len(arr),-1)
    g = np.stack(((f**(N-i-1) for i in range(N))), axis=1).reshape(len(arr),N)
    print(g)

In [7]:
f = np.array([1,2,3,4,5,6,7,8,9,10])
N = 3
Vander_2(f, N)

[[  1   1   1]
 [  4   2   1]
 [  9   3   1]
 [ 16   4   1]
 [ 25   5   1]
 [ 36   6   1]
 [ 49   7   1]
 [ 64   8   1]
 [ 81   9   1]
 [100  10   1]]


### Q2 Write a function to find moving average in an array over a window: Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.

In [8]:
def moving_avg(List, N):
    cumsum = [0]
    mov_avg = []
    
    for i, x in enumerate(List, start=1):
        cumsum.append(cumsum[i-1] + x)
        if i>=N:
            mov_avg.append(round((cumsum[i] - cumsum[i-N])/N, 3))
            
    print(mov_avg)
    print(f"The length of the list {len(List)-N+1}")

In [9]:
a = [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]
n = 3
moving_avg(a,n)

[5.0, 4.667, 5.667, 6.667, 9.667, 28.667, 49.333, 72.667, 84.0, 93.333, 116.333]
The length of the list 11
